- alias: Control switches via MQTT
  trigger:
    platform: mqtt
    topic: +/switch/+/state/cmd
  action:
    - service_template: >
        homeassistant.turn_{{trigger.payload}}
      data_template:
        entity_id: >-
          {{ trigger.topic.split('/')[-4] }}.{{ trigger.topic.split('/')[-3] }}
          

- alias: Control lights state via MQTT
  trigger:
    platform: mqtt
    topic: +/light/+/state/cmd
  action:
    - service_template: >
        homeassistant.turn_{{trigger.payload}}
      data_template:
        entity_id: >-
          {{ trigger.topic.split('/')[-4] }}.{{ trigger.topic.split('/')[-3] }}


- alias: Control lights brightness via MQTT
  trigger:
    platform: mqtt
    topic: +/light/+/brightness/cmd
  action:
    - service_template: >
        homeassistant.turn_on
      data_template:
        brightness: '{{trigger.payload}}'
        entity_id: >-
          {{ trigger.topic.split('/')[-4] }}.{{ trigger.topic.split('/')[-3] }}


- alias: Control lights hs color via MQTT
  trigger:
    platform: mqtt     
    topic: +/light/+/hs_color/cmd
  action:
    - service_template: >
        light.turn_on
      data_template:
        hs_color: 
          - '{{ trigger.payload[0] | int }}'
          - '{{ trigger.payload[1] | int }}'
        entity_id: >-
          {{ trigger.topic.split('/')[-4] }}.{{ trigger.topic.split('/')[-3] }}
          
- alias: Control thermostat setpoint via MQTT
  trigger:
    platform: mqtt
    topic: +/climate/+/temperature/cmd
  action:
    - service_template: >
        climate.set_temperature
      data_template:
        temperature: '{{trigger.payload}}'
        entity_id: >-
          {{ trigger.topic.split('/')[-4] }}.{{ trigger.topic.split('/')[-3] }}
          
- alias: Control thermostat mode via MQTT
  trigger:
    platform: mqtt
    topic: +/climate/+/state/cmd
  action:
    - service_template: >
        climate.set_hvac_mode
      data_template:
        hvac_mode: '{{trigger.payload}}'
        entity_id: >-
          {{ trigger.topic.split('/')[-4] }}.{{ trigger.topic.split('/')[-3] }}
		  
- alias: Control thermostat fanmode via MQTT
  trigger:
    platform: mqtt
    topic: +/climate/+/fan_mode/cmd
  action:
    - service_template: >
        climate.set_fan_mode
      data_template:
        fan_mode: '{{trigger.payload}}'
        entity_id: >-
          {{ trigger.topic.split('/')[-4] }}.{{ trigger.topic.split('/')[-3] }}

- alias: Update Octopus Agile Price
  description: ''
  trigger:
  - hours: '*'
    minutes: '30'
    platform: time_pattern
    seconds: '0'
  - hours: '*'
    minutes: '0'
    platform: time_pattern
    seconds: '0'
  condition: []
  action:
  - data:
      entity_id: sensor.electricity_cost
    service: homeassistant.update_entity
